### SPRING

spring:
  datasource:
#    url: jdbc:mysql://qa-mysqldb.mylab.report/mylabreport2qa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://mylabreportqa/frm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    change-log: classpath:changelogs/db-changelog.xml